# needs at least 16 GB of memory

exp_name: test_if_work_4
work_dir: /home/day3/cxx/codefield/MyBasicVSR/work_dir

train_dataloader:
  batch_size: 4
  shuffle: True
  num_workers: 0
  pin_memory: True
  dataset:
    type: REDSDataset
    gt_dir: /home/day3/cxx/codefield/MyBasicVSR/data/REDS/train_sharp
    lq_dir: /home/day3/cxx/codefield/MyBasicVSR/data/REDS/train_sharp_bicubic/X4
    scale_factor: 4
    patch_size: 64
    num_input_frames: 15
    filename_tmpl: "{:08d}.png"
    max_keys: 270
    val_partition: REDS4
    is_test: False

val_dataloader:
  batch_size: 1
  shuffle: False
  num_workers: 0
  pin_memory: True
  dataset:
    type: REDSDataset
    gt_dir: /home/day3/cxx/codefield/MyBasicVSR/data/REDS/train_sharp
    lq_dir: /home/day3/cxx/codefield/MyBasicVSR/data/REDS/train_sharp_bicubic/X4
    scale_factor: 4
    patch_size: 64
    num_input_frames: 100
    filename_tmpl: "{:08d}.png"
    max_keys: 270
    val_partition: REDS4
    is_test: True

model:
  type: BasicVSR
  scale_factor: 4
  mid_channels: 64
  num_blocks: 30
  spynet_pretrained: /home/day3/cxx/codefield/MyBasicVSR/checkpoint/spynet_20210409-c6c1bd09.pth

