# needs at least 16 GB of memory

exp_name: test_if_work
work_dir: /home/day3/cxx/codefield/MyBasicVSR/exp
num_gpu: auto

train_dataloader:
  batch_size: 4
  shuffle: True
  num_workers: 0
  pin_memory: True
  dataset:
    type: REDSDataset
    gt_dir: /home/day3/cxx/codefield/MyBasicVSR/data/REDS/train_sharp
    lq_dir: /home/day3/cxx/codefield/MyBasicVSR/data/REDS/train_sharp_bicubic/X4
    scale_factor: 4
    patch_size: 64
    num_input_frames: 15
    filename_tmpl: "{:08d}.png"
    max_keys: 270
    val_partition: REDS4
    is_test: False

val_dataloader:
  batch_size: 1
  shuffle: False
  num_workers: 0
  pin_memory: True
  dataset:
    type: REDSDataset
    gt_dir: /home/day3/cxx/codefield/MyBasicVSR/data/REDS/train_sharp
    lq_dir: /home/day3/cxx/codefield/MyBasicVSR/data/REDS/train_sharp_bicubic/X4
    scale_factor: 4
    patch_size: 64
    num_input_frames: 100
    filename_tmpl: "{:08d}.png"
    max_keys: 270
    val_partition: REDS4
    is_test: True

model:
  type: BaseVSRModel
  backbone:
    type: BasicVSR
    scale_factor: 4
    mid_channels: 64
    num_blocks: 30
    spynet_pretrained: /home/day3/cxx/codefield/MyBasicVSR/checkpoint/spynet_20210409-c6c1bd09.pth
  pretrained: ~

train:
  ema_decay: 0.999
  optimizer:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingLR
    T_max: 300000
    eta_min: !!float 1e-7

  total_iter: 300000
  warmup_iter: -1 # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.125

  criterion:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

val:
  val_freq: 5000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

logger:
  print_freq: 100
  save_checkpoint_freq: 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
