name: ~
work_dir: {root}/exp
num_gpu: auto

train_dataloader:
  batch_size: ~
  shuffle: True
  num_workers: 0
  pin_memory: True
  dataset:
    type: ~
    # kwargs

val_dataloader:
  batch_size: ~
  shuffle: False
  num_workers: 0
  pin_memory: True
  dataset:
    type: ~
    # kwargs

model:
  type: BaseVSRModel
  backbone:
    type: ~
    # kwargs
  pretrained: ~
  strict_load: True

train:
  ema_decay: 0.999
  optimizer:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingLR
    T_max: 300000
    eta_min: !!float 1e-7

  total_iter: 300000
  warmup_iter: -1 # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.125

  criterion:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

val:
  val_freq: 5000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      crop_border: 0
    ssim:
      crop_border: 0

logger:
  print_freq: 100
  save_checkpoint_freq: 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
